# Don't print a new line at the start of the prompt
add_newline = false

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
# conflicted = ""
# ahead = "ğŸ†"
# behind = "ğŸ‘"
# diverged = "ğŸ‰"
# untracked = "ğŸ¥¥"
# stashed = ""
# modified = "ğŸŒ"
# staged = '[++\($count\)](green)'
# renamed = ""
# deleted = ""